### ISSUE TITLE
[Epic] EIP-1271

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#1088]
## What is the feature about

Implementing off-chain EIP-1271 support into the Safe UI.

## Transaction service endpoints

- [x] Get (all)/propose messages https://github.com/safe-global/safe-transaction-service/pull/1138
  - [x] https://github.com/safe-global/safe-transaction-service/pull/1170
  - [x] https://github.com/safe-global/safe-transaction-service/pull/1176
  - [ ] Fix for safes <1.3.0 https://github.com/safe-global/safe-eth-py/issues/421

## Gateway endpoint

- [x] Get all messages https://github.com/safe-global/safe-client-gateway/issues/998
  - [x] https://github.com/safe-global/safe-client-gateway/pull/1007
- [x] Propose message https://github.com/safe-global/safe-client-gateway/pull/1006
- [x] Confirm message https://github.com/safe-global/safe-client-gateway/pull/1008
- [x] Get message by hash https://github.com/safe-global/safe-client-gateway/pull/1014
- [x] Add `messagesTag` to Safe info endpoint https://github.com/safe-global/safe-client-gateway/pull/1013

## Gateway SDK

- [x] Add endpoints https://github.com/safe-global/safe-gateway-typescript-sdk/issues/98
  - [x] Add singular endpoint https://github.com/safe-global/safe-gateway-typescript-sdk/pull/104

## Web

- [x] "Messages" routes/tab #1155
- [x] Accordion summary #1156
- [x] Accordion details #1157
- [x] Accordion signature stepper #1158
- [x] Fetching of messages #1159
  - [x] Store slice #1217
  - [x] Integrate endpoint #1243
  - [x] Poll on tag change #1273 
- [x] Add new event bus #1205
- [x] New signing modal #1206
  - [x] Modal #1224
  - [x] Integrate with `communicator` #1270
  - [x] Integrate endpoint #1243
- [x] Extend the test Safe App #1207
- [x] Create dApp that uses WC https://github.com/5afe/eip-1271-dapp
- [x] Normalize messages before submitting to backend #1517

## Safe Apps

- [x] Set off-chain signing https://github.com/safe-global/safe-apps-sdk/pull/407
- [x] Update WC Safe App https://github.com/safe-global/safe-react-apps/pull/608

## Links

- [Problem statement w/ kickoffs](https://www.notion.so/EIP-1271-signatures-can-only-be-generated-on-chain-2800b5e516124d959c38ba8f2042f9f7)
- [Backend specifications](https://www.notion.so/gnosis-safe/EIP-1271-backend-specifications-c0c6ef187425475288216021a7521c82?d=3345071f763246439acfe3c765645369#ad5426ada7c54158b8b04b9a4ca25bac)
- [Figma](https://www.figma.com/file/x1uuIJsOZkyv5cwNlDdVC1/EIP-1271?node-id=1%3A2)

## Test Cases

- [EIP-1271 test cases](https://www.notion.so/gnosis-safe/39fa9f1ede724bda989381fb41f0a14c?v=20d51e02d9e748948f1d1d59f6803226)

##Found issues

- [x] https://github.com/safe-global/web-core/issues/1435
- [x] https://github.com/safe-global/web-core/issues/1432
- [x] https://github.com/safe-global/web-core/issues/1431
- [x] https://github.com/safe-global/web-core/issues/1430
- [x] https://github.com/safe-global/web-core/issues/1438
- [x] https://github.com/safe-global/web-core/issues/1447

**Comment by fmrsabino** [comment]
The `Gateway SDK` section has the wrong link to the issue right?

I can ping you when the issue is created on the Safe Client Gateway side

**Comment by iamacook** [comment]
> The `Gateway SDK` section has the wrong link to the issue right?

Nice catch, I've updated it.

> I can ping you when the issue is created on the Safe Client Gateway side

Thanks, I appreciate it.
