### ISSUE TITLE
[Epic] Manually hiding tokens

### ISSUE THREAD

**Issue by schmanu** [safe-global/web-core#1337]
## What is the feature about
**Related to Epic #865**
This feature enables users to manually hide unwanted / spam tokens from our interface.
For every asset (except native ones) we will add a checkbox / button to hide the asset. 
Hidden assets will not be displayed / counted:
- in the asset list
- in token auto completions (Send funds, Spending Limits)
- In the total balance

Note: We will not hide transactions in the history.

## The list of requirements
- [x] add new menu to hide / unhide tokens
- [x] ignore hidden tokens in UI
- [x] remember hidden token in local storage

## Designs/sketches
https://www.figma.com/file/ZKWJPH1MjJIyUDTHYD3kk8/Default-token-lists?node-id=2%3A26&t=bKTHJUzmMmfe6jLa-0

## Links
https://www.notion.so/gnosis-safe/Default-token-lists-and-local-hiding-of-tokens-cd353630b55c4625bac5d4f6ae546c4f
