### ISSUE TITLE
[Epic] Governance app

### ISSUE THREAD

**Issue by iamacook** [safe-global/web-core#1383]
## What is the feature about

If/when a transferability SEP is proposed again, we will have 4 weeks until it becomes active. It is currently not possible to delegate outside of the Safe interface.

We want to diversify governance participants and, as such, require an improved interface for non-Safe owners.

## The list of requirements

These will be expanded upon after initial kick-off/designs are created, but:

- [x] Create a "Safe app-app" that can work inside the Safe UI/in the browser https://github.com/5afe/safe-app-dapp
- [x] Create `safe-react-apps` app for new app https://github.com/5afe/safe-delegation-app/issues/4
- [x] Create introduction pages https://github.com/5afe/safe-delegation-app/issues/1
  - [x] Pages https://github.com/5afe/safe-delegation-app/pull/6
  - [x] Account center https://github.com/5afe/safe-delegation-app/pull/7
- [x] Create education series https://github.com/5afe/safe-delegation-app/issues/5
- [x] Create (re-)delegation flow https://github.com/5afe/safe-delegation-app/issues/2
- [x] Create claiming flows https://github.com/5afe/safe-delegation-app/issues/3

## Designs/sketches

- [Figma](https://www.figma.com/file/9nvicX7ng5528qAKXSf55J/Delegate-S-Tokens-App?node-id=2645%3A3982&t=f7uBRW0XpL2WsjsP-0)

## Links

- [Repo](https://github.com/safe-global/safe-dao-governance-app)
- [Feature spec](https://www.notion.so/gnosis-safe/Feature-Spec-4609c60ac65c4940bb81c27971c6ad4c)
- [Problem statement](https://www.notion.so/gnosis-safe/SAFE-delegation-app-a46041904fad4516ad1acefb8fe71b87)

**Comment by liliya-soroka** [comment]
Verified
