### ISSUE TITLE
[Epic] Safe Apps Discoverability

### ISSUE THREAD

**Issue by dasanra** [safe-global/web-core#1443]
## What is the feature about
We are not using all the information we have about Safe Apps to help the user to find or discover new apps.
Categorization can be used to understand at first glance what an app is for.
We should show those apps that are doing special effort to integrate with the Safe creating a better experience.
An app may be available in several networks, but is not possible to know this in the main list.
Making this visible may encourage app developers also to polish their integrations with the Safe.
It's not easy to find information on how to create a custom app. We should promote this possibility and attract attention from developers already from the interface

## The list of requirements

- [ ] [Adapt the list to the new design including the different sections in tabs](https://github.com/safe-global/web-core/issues/1444)
- [ ] [Add social media links](https://github.com/safe-global/safe-config-service/issues/739)
- [ ] [Add batched transactions property to the service](https://github.com/safe-global/safe-config-service/issues/755)
- [ ] [Add drawer with application details](https://github.com/safe-global/web-core/issues/1414)
- [ ] [Add section to inform about how to create an app](https://github.com/safe-global/web-core/issues/1446)

## Designs/sketches
![imagen](https://user-images.githubusercontent.com/25051234/209176731-d24df15c-79e0-4fb7-8b33-6e55c686dce8.png)
![imagen](https://user-images.githubusercontent.com/25051234/209177195-ccf10529-b06f-4fd4-ac2f-7bccdf2e0a4e.png)
![imagen](https://user-images.githubusercontent.com/25051234/209177245-4e2e52b5-d556-4df6-b58d-b7ed43781554.png)

## Links
- [Roadmap board item](https://www.notion.so/gnosis-safe/Safe-Apps-Interface-Discoverability-Features-0c4bd0da771843bcb06e1253aa5bacde)
- [Designs](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=2102%3A55784&t=3T7EejBPicVAAd6J-0)
