### ISSUE TITLE
[Epic] Safe Creation Redesign

### ISSUE THREAD

**Issue by usame-algan** [safe-global/web-core#864]
## Overview

Improving the drop-off rate during safe creation by implementing the [new design](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=51%3A5661)

## Tasks

- [x] Build a stepper component to manage the form screens #931
- [x] Build a component for the info widget #927 
- [x] Build a component for the overview widget #928
- [x] Build a component for the status screens #932
- [x] Implement redesign for the status screens #994 
- [x] Implement redesign Network + Name step #961 
- [x] Implement redesign Owner step #962
- [x] Implement redesign Review step #963
- [x] Implement redesign Connect Wallet step #1003 
- [x] Layout #995
- [x] Implement Overview/Info Widget display logic #996 
- [x] Handle wallet connection #1080 
- [ ] A/B testing: #968

## How to test

- Open the new route `/new-safe/create`
- Click through the steps and compare to the Figma designs
- Check that the requirements of each subtask is met

## Links

Problem statement: https://github.com/safe-global/safe-pm/issues/82
Notion: https://www.notion.so/gnosis-safe/Safe-Creation-7ec069306e8c4101bffd7c17299eec53
Figma: https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=51%3A5661
Analytics: https://analytics.google.com/analytics/web/#/analysis/p308247657/edit/h41dtVeqQ0icP3o_O_Cx-g

**Comment by francovenica** [comment]
Question.
The previous iteration of safe creation would put as the first owner the currently connected wallet, and if you changed wallet it would replace that first row with it. Was that feature dropped?

**Comment by francovenica** [comment]
Question/suggestion : In the review step (step 4) the addresses don't have the copy to clipboard/blockexplorer icons. They are not in the design, but we put it everywhere in the app, we should probably put them here too

**Comment by francovenica** [comment]
Question:
In the designs it seems to be a way to complete cancel the safe creation, but in any of the step, not even step one, there is a "Cancel". Was decided to not put a way to exit the safe creation?
Currently, the only way for the user to get out is using the logo on the top left (which is not even that good, since that if the user has a "last used safe" it will take him there first)

**Comment by usame-algan** [comment]
> The previous iteration of safe creation would put as the first owner the currently connected wallet, and if you changed wallet it would replace that first row with it. Was that feature dropped?

Yes, we decided to change it because it would allow creating a safe for a different wallet than the connected one e.g. a user wants to create a safe with one owner that is not his wallet. So initially the connected wallet is set as an owner only once now and can be changed.

> In the review step (step 4) the addresses don't have the copy to clipboard/blockexplorer icons. They are not in the design, but we put it everywhere in the app, we should probably put them here too

Makes sense! I will add links there as well.

**Comment by francovenica** [comment]
I've been checking the GTM with the old and new safe creation. The only noticeable difference is that from the "owner" step to the next there are 2 metadatas (Owners and policies).
This image is from current prod web-core. These 2 metadata are not being tracked in the new safe creation flow
![image](https://user-images.githubusercontent.com/4503659/202950830-0c774c66-3a02-4ad8-81f0-8b57903af14e.png)

Also we are not tracking anything regarding the new tips in the right side of the safe creation (if the user clicks them or not). I think we should since the idea is to know if the users are paying attention to them or not.
![image](https://user-images.githubusercontent.com/4503659/202951020-c7e2cc46-7cc7-4426-930b-85959f3fe299.png)
