### ISSUE TITLE
[Epic] Safe Apps can only be viewed inside a limited frame

### ISSUE THREAD

**Issue by dasanra** [safe-global/web-core#866]
## Overview
Enhance the adaptability of the Safe interface to just wrap some of its elements to enable more screen space for the Safe App. This will make the Safe App to look as it's not used inside of a Safe until transaction time

Roadmap Epic:
https://www.notion.so/gnosis-safe/Expanding-the-Safe-App-frame-fe75278b7d22416bb4ea33171813e8ef

## Requirements
- [ ] Design a new frame view to get more space for Safe Apps
- [ ] Create interface elements to allow navigating again to the Safe
- [ ] Pop-up transaction modal still with Safe App open
- [ ] Show transaction queue with Safe App open if something is pending to be signed

## Designs
Need to sync with Lila

**Comment by clemoon** [comment]
Re: mock ups of Lila - https://www.figma.com/file/2T4n3zv8xbeeWWD3UHyqpf/App-frime-size?node-id=1%3A1797

Leaving the feedback here too so we have a trail on Github: 

A few comments from my side and from the daily this morning. The default mode for when the app launches should be that the side bar collapses rather than it being optional. However if the side bar is hidden as default we need to make sure the user has a straightforward way of access it again. There was also the comment this morning that the speed dial could be confused as being provided by the app rather than safe. Given this I suggest:

- When the app launches, hide the side bar by default

- When the app launches, display the speed dial open with the different navigation options

- Use the styling guide of the new Safe branding with vivid colors on the mui component so it's clear the speed dial is provided by Safe

- Let's work together on finding an icon that shows a clear path to show the sidebar

**Comment by clemoon** [comment]
Let's freeze the requirements and go ahead with [this iteration](https://www.figma.com/proto/2T4n3zv8xbeeWWD3UHyqpf/App-frime-size?node-id=33%3A3451&scaling=min-zoom&page-id=1%3A2&starting-point-node-id=33%3A3451). Let's deprioritise the speed dial for this v1. In V1 we should have: 

- [ ] Clickable sidebar to pull sidebar
- [ ] Sidebar collapse animation on app launch 

@liliiaorlenko I'm happy to jump with you on a call to discuss the implementation :)

**Comment by mikhailxyz** [comment]
Feedback after playing with the sidebar on dev: the element is not accessible, you cannot expand/close it using keyboard only

**Comment by katspaugh** [comment]
Probably solvable by adding a tabIndex to the toggle button? So that you can press tab to put focus on it?

**Comment by mikhailxyz** [comment]
@katspaugh yeah, that should do it 👍
