### ISSUE TITLE
[Epic] Safe apps analysis

### ISSUE THREAD

**Issue by dasanra** [safe-global/web-core#942]
## What is the feature about
We will collect data about Safe Apps usage, both in absolute and relative terms. To collect this information, we will primarily make use of the analytics tool being currently used by the team.

## Reports to cover

- [x] #1009
- [x] #983 **(Frontend)**
- [x] #999
- [x] #984 **(Frontend)**
- [x] #998
- [x] #1010
- [x] [Out of scope] #1126
- [x] #987
- [x] #1011
- [x] [Out of scope] #1012
- [x] #1104
- [x] [Out of scope] [12. Number of transactions made per Safe](https://www.notion.so/Number-of-transactions-made-per-Safe-2fdbb94b358f4319aa1b95695c008548) **(Backend)**
- [x] [Out of scope] #1105
- [x] [Out of scope] #1106
- [x] [Out of scope] [Out of scope] [15. Apps with most Safe volume ](https://www.notion.so/Apps-with-most-Safe-volume-015f20871c3b4eeb9d30e5afaf23dc3d) **(Backend)**
- [x] #1139
- [x] #1141
- [x] #1140
- [x] #1142

## Links
Problem statement
https://www.notion.so/gnosis-safe/Analytics-on-safe-apps-421c3a796fda49d79886a321c7cfce9d

**Comment by clemoon** [comment]
I suggest to update the epic and to descope:

- Open count vs transaction inside the app #1009 (dependency on the backend to know the transaction count)

Remaining to be closed before the epic completion:

- Apps most used via WalletConnect #987
