### ISSUE TITLE
[Epic] Governance Visibility

### ISSUE THREAD

**Issue by DiogoSoaress** [safe-global/web-core#969]
## Overview

Create better visibility for SafeDAO governance within our web interface

### Create a Governance section in the Dashboard

- [x] #974
- [x] #970
- [x] #976

### Exploratory work:
- [x] #1221
- [x] https://github.com/safe-global/web-core/issues/1222

### Fixes:
- [x] https://github.com/safe-global/safe-react-apps/issues/590
- [x] https://github.com/safe-global/safe-react-apps/issues/591
- [x] https://github.com/safe-global/web-core/issues/1275
- [x] https://github.com/safe-global/web-core/issues/1269
- [ ] make sure that text all over the widget has the font and size according to the design

## Links

Problem Statement: https://www.notion.so/gnosis-safe/Safe-governance-has-no-visibility-in-our-product-interfaces-9ac542d352e0405486dc6380d4b7198b
Ideation: https://www.notion.so/gnosis-safe/Safe-governance-visibility-8ba5f8f4d58249c1bdac6c3ae2429992
Figma: https://www.figma.com/file/8nKOe7h90OS7jmn3nksbq9/Governance-visibility-widgets?node-id=1%3A2&t=6xgktRKjZ8vRyHbW-0

## Test cases 
https://www.notion.so/gnosis-safe/7a60bea771e8408aa641a86f0c6f163c?v=c0914058adc14f54954da24e75d0ac62

### Screenshots (1024px)
<img width="1791" alt="Screenshot 2022-11-17 at 10 47 36" src="https://user-images.githubusercontent.com/32431609/202413199-0d08b0b3-7672-407b-970d-af3ae7d1c464.png">
<img width="1791" alt="Screenshot 2022-11-17 at 10 48 05" src="https://user-images.githubusercontent.com/32431609/202413222-d07dd20f-903c-4074-8e8b-e158a69dce8c.png">
<img width="1791" alt="Screenshot 2022-11-17 at 10 49 18" src="https://user-images.githubusercontent.com/32431609/202413480-8b194a44-8668-488a-9dbf-1633abb32fa7.png">

**Comment by liliya-soroka** [comment]
29.11 - testing is done, waiting for fixes to retest

**Comment by katspaugh** [comment]
@liliya-soroka I've merged the fixes.
