### ISSUE TITLE
[Epic] Transaction replacement (v1)

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#971]
## What is the feature about
Users complain that canceling/replacing transactions is currently confusing.

## The list of requirements

* [x] https://github.com/safe-global/web-core/issues/972
* [x] https://github.com/safe-global/web-core/issues/973
* [x] https://github.com/safe-global/web-core/issues/718
* [ ] Add info tips about irrevokable signatures

## Links
Roadmap item: https://www.notion.so/gnosis-safe/Replacing-cancelling-existing-transactions-in-the-queue-is-cumbersome-3e3880dc709f4e25b34d80c57df0983c
Slides: https://docs.google.com/presentation/d/1tvKBh6NbVf3GYc0_IL5aFwup-yWSz19JSpjhzqLpuPI/edit
